FROM node:19.5.0-alpine     

WORKDIR '/app/'

COPY package.json .
RUN npm install 

COPY  . .
# Add a non-root user
RUN addgroup -g 1001 -S appuser && adduser -u 1001 -S appuser -G appuser
USER appuser

CMD ["npm","run", "start"]

